# Page settings
baseurl = "/"
title = "Response Care"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom.css"]

  favicon = "img/favicon.ico"

  # Meta
  author = ""
  description = ""
  email = ""

  # Hero section
  [params.hero]
    title = "Response Care"
    subtitle = 'Making child poverty history through Art & Design'

  # Contact section
  [params.contact]
    enable = true
    form = true
    title = "Get in touch"
    description = "Join our mailing list to get regular updates on Response Care."

  # Footer section
  [params.footer]
    enable = false