# Page settings
baseurl = "/"
languageCode = "en-us"
theme = "hugo-elate-theme"
title = "Response Care"

[params]

custom_css = ["css/custom1.css"]

favicon = "img/favicon.ico"

# Meta
author = ""
description = ""
email = ""

# Navigation
[params.navigation]
brand = "Response Care"
about = "About Us"
mission = "Our Mission"
vision = "Our Vision"
projects = "Projects"
contact = "Contact"

# Hero section
[params.hero]
subtitle = 'Making child poverty history through Art & Design'
title = "Response Care"

# About section
[params.about]
enable = true
title = "About"

# Work section
[params.work]
enable = true
title = "Our Projects"

[[params.work.row]]
alt = "Image2"
img = "work_1.jpg"
title = "First Child Centre"

# Contact section
[params.contact]
description = "Join our mailing list to get regular updates on Response Care."
enable = true
form = true
title = "Get in touch"

# Footer section
[params.footer]
enable = false
