# Page settings
baseurl = "https://responsecare.org"
title = "Response Care"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/style.css"]

  favicon = "img/favicon.ico"

  # Meta
  author = ""
  description = ""
  email = ""

  # Navigation
  [params.navigation]
    brand = "Response Care"

  # Hero section
  [params.hero]
    title = "Coming Soon."
    subtitle = 'Response Care - Making child poverty history through Art & Design'